---
title: "Visual Analytics & Applications - VAST Challenge 2021"
description: |
  Welcome to the ISSS608 G1 Group 4's Visual Analytics Project Website!
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Welcome to Group 4's Visual Analytics Project Website

The website documents our group's work to develop an interactive visualizations in the form of a Shiny application for the VAST Challenge 2021 to help visualize patterns and identify anomalies in the data. The framework for the application is done using R and Shiny, with special focus on the visNetwork, Plotly, igraph and tmap packages in R.

The app authors are Alethea Lim (Jin Ru), Darius Yeo (Ding Run) and Mayurapriyann Arulmozhi Baskaran with special credits to Associate Professor Kam Tin Seong for his mentorship and guidance in ISSS608 Visual Analytics and Applications course.

With the pressing time urgency in solving crimes, it is necessary to maximize the use of analytics tools to enhance the law enforcers’ abilities to pick up hints and clues in order to speed up their investigation and to close the case. The R packages for data analytics provide an excellent tool for analysts to customize various visualizations according to the business use cases. The R packages share an underlying design philosophy, grammar, and data structures and this strong advantage allows analysts to combine various functionalities of different packages in an integrated manner.

Our **[Practice Research Paper](ResearchPaper.html)** outlines the motivation behind the application created, the review of past work, design framework, use cases, discussions on new insights and future work. A detailed **[User Guide](UserGuide.html)** is provided to help get the end users started on using the Shiny application. To get a brief context on our project and application, you may refer to our **[Project Poster](ProjectPoster.html)**.